#!/bin/bash

# set netcard
NETCARD1=`cat /opt/pi2bus/settings/lan`
NETCARD2=`cat /opt/pi2bus/settings/wan`

# set subnet LAN
SUBNET=`cat /opt/pi2bus/settings/subnet`

# set download
DOWNLOAD=`cat /opt/pi2bus/settings/download`

# set upload
UPLOAD=`cat /opt/pi2bus/settings/upload`

# set max bandwidth
MAXBANDWIDTH=`cat /opt/pi2bus/settings/maxbandwidth`

# declare bandwidth, same for all
declare -A ipctrl
declare -A bandwidth

for((i=2;i<=254;i++))
do
	bandwidth["download"]=$DOWNLOAD
	bandwidth["upload"]=$UPLOAD
	for key in "${!bandwidth[@]}";
	do
		ipctrl[$i,$key]=${bandwidth[$key]}
	done
done

declare -p ipctrl

# reinit
iptables -F -t mangle
tc qdisc del dev $NETCARD1 root handle 1
tc qdisc del dev $NETCARD2 root handle 1
tc qdisc add dev $NETCARD1 root handle 1: htb default 9999
tc qdisc add dev $NETCARD2 root handle 1: htb default 9999

# create the default class
tc class add dev $NETCARD1 parent 1:0 classid 1:9999 htb rate $(( $MAXBANDWIDTH ))kbit ceil $(( $MAXBANDWIDTH ))kbit burst 5k prio 9999
tc class add dev $NETCARD2 parent 1:0 classid 1:9999 htb rate $(( $MAXBANDWIDTH ))kbit ceil $(( $MAXBANDWIDTH ))kbit burst 5k prio 9999

for((i=2;i<=254;i++))
do
	# set IP
	IP=$SUBNET$i

	# set download for IP
	DOWNLOAD=${ipctrl[$i,download]}

	# set upload for IP
	UPLOAD=${ipctrl[$i,upload]}

	# traffic shaping rule
	tc class add dev $NETCARD1 parent 1:0 classid 1:$i htb rate $(( $DOWNLOAD ))kbit ceil $(( $DOWNLOAD ))kbit burst 5k prio $i
	tc class add dev $NETCARD2 parent 1:0 classid 1:$i htb rate $(( $UPLOAD ))kbit ceil $(( $UPLOAD ))kbit burst 5k prio $i

	# netfilter packet marking rule
	iptables -t mangle -A FORWARD -i $NETCARD1 -s $IP -j CONNMARK --set-mark $i
	iptables -t mangle -A FORWARD -i $NETCARD2 -d $IP -j CONNMARK --set-mark $i

	# filter that bind the two
	tc filter add dev $NETCARD1 parent 1:0 protocol ip prio $i handle $i fw flowid 1:$i
	tc filter add dev $NETCARD2 parent 1:0 protocol ip prio $i handle $i fw flowid 1:$i

	echo "Set traffic shaping for IP $IP download $DOWNLOAD kbps / upload $UPLOAD kbps. Good luck!"
done

#propagate netfilter marks on connections
iptables -t mangle -A POSTROUTING -j CONNMARK --restore-mark

